
name: vibrapp
description: Vibrapp para enviar vibraciones
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.7.4

flutter:
  uses-material-design: true
