
name: vibrapp
description: App Flutter para enviar vibraciones por código
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0
  vibration: ^1.7.4

flutter:
  uses-material-design: true
